[package]
name = "ip-grabber"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "^4.11.0"
actix-files = "^0.6.8"
tera = "^1.20.0"
lazy_static = "^1.5.0"
sqlx = { version = "^0.8.6", features = ["postgres", "runtime-tokio-native-tls"] }
serde = "^1.0.228"
env_logger = "^0.11.8"